INSERT INTO CATEGORY (DESCRIPTION) VALUES ('A');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('B');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('C');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('D');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('1');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('2');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('3');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('4');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('5');

