INSERT INTO CATEGORY (DESCRIPTION) VALUES ('American');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Italian');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Mexican');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Fast Food');

INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('Each');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('Tablespoon');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('Teaspoon');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('Dash');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('Pint');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('Cup');

